// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeliverySourceSpec defines the desired state of DeliverySource.
//
// This structure contains information about one delivery source in your account.
// A delivery source is an Amazon Web Services resource that sends logs to an
// Amazon Web Services destination. The destination can be CloudWatch Logs,
// Amazon S3, or Firehose.
//
// Only some Amazon Web Services services support being configured as a delivery
// source. These services are listed as Supported [V2 Permissions] in the table
// at Enabling logging from Amazon Web Services services. (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html)
//
// To configure logs delivery between a supported Amazon Web Services service
// and a destination, you must do the following:
//
//   - Create a delivery source, which is a logical object that represents
//     the resource that is actually sending the logs. For more information,
//     see PutDeliverySource (https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDeliverySource.html).
//
//   - Create a delivery destination, which is a logical object that represents
//     the actual delivery destination. For more information, see PutDeliveryDestination
//     (https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDeliveryDestination.html).
//
//   - If you are delivering logs cross-account, you must use PutDeliveryDestinationPolicy
//     (https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDeliveryDestinationPolicy.html)
//     in the destination account to assign an IAM policy to the destination.
//     This policy allows delivery to that destination.
//
//   - Create a delivery by pairing exactly one delivery source and one delivery
//     destination. For more information, see CreateDelivery (https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateDelivery.html).
//
// You can configure a single delivery source to send logs to multiple destinations
// by creating multiple deliveries. You can also create multiple deliveries
// to configure multiple delivery sources to send logs to the same delivery
// destination.
type DeliverySourceSpec struct {

	// Defines the type of log that the source is sending.
	//
	//    * For Amazon Bedrock Agents, the valid values are APPLICATION_LOGS and
	//    EVENT_LOGS.
	//
	//    * For Amazon Bedrock Knowledge Bases, the valid value is APPLICATION_LOGS.
	//
	//    * For Amazon Bedrock AgentCore Runtime, the valid values are APPLICATION_LOGS,
	//    USAGE_LOGS and TRACES.
	//
	//    * For Amazon Bedrock AgentCore Tools, the valid values are APPLICATION_LOGS,
	//    USAGE_LOGS and TRACES.
	//
	//    * For Amazon Bedrock AgentCore Identity, the valid values are APPLICATION_LOGS
	//    and TRACES.
	//
	//    * For Amazon Bedrock AgentCore Memory, the valid values are APPLICATION_LOGS
	//    and TRACES.
	//
	//    * For Amazon Bedrock AgentCore Gateway, the valid values are APPLICATION_LOGS
	//    and TRACES.
	//
	//    * For CloudFront, the valid value is ACCESS_LOGS.
	//
	//    * For Amazon CodeWhisperer, the valid value is EVENT_LOGS.
	//
	//    * For Elemental MediaPackage, the valid values are EGRESS_ACCESS_LOGS
	//    and INGRESS_ACCESS_LOGS.
	//
	//    * For Elemental MediaTailor, the valid values are AD_DECISION_SERVER_LOGS,
	//    MANIFEST_SERVICE_LOGS, and TRANSCODE_LOGS.
	//
	//    * For Amazon EKS Auto Mode, the valid values are AUTO_MODE_BLOCK_STORAGE_LOGS,
	//    AUTO_MODE_COMPUTE_LOGS, AUTO_MODE_IPAM_LOGS, and AUTO_MODE_LOAD_BALANCING_LOGS.
	//
	//    * For Entity Resolution, the valid value is WORKFLOW_LOGS.
	//
	//    * For IAM Identity Center, the valid value is ERROR_LOGS.
	//
	//    * For Network Firewall Proxy, the valid values are ALERT_LOGS, ALLOW_LOGS,
	//    and DENY_LOGS.
	//
	//    * For Network Load Balancer, the valid value is NLB_ACCESS_LOGS.
	//
	//    * For PCS, the valid values are PCS_SCHEDULER_LOGS and PCS_JOBCOMP_LOGS.
	//
	//    * For Quick, the valid values are CHAT_LOGS and FEEDBACK_LOGS.
	//
	//    * For Amazon Web Services RTB Fabric, the valid values is APPLICATION_LOGS.
	//
	//    * For Amazon Q, the valid values are EVENT_LOGS and SYNC_JOB_LOGS.
	//
	//    * For Amazon SES mail manager, the valid values are APPLICATION_LOGS and
	//    TRAFFIC_POLICY_DEBUG_LOGS.
	//
	//    * For Amazon WorkMail, the valid values are ACCESS_CONTROL_LOGS, AUTHENTICATION_LOGS,
	//    WORKMAIL_AVAILABILITY_PROVIDER_LOGS, WORKMAIL_MAILBOX_ACCESS_LOGS, and
	//    WORKMAIL_PERSONAL_ACCESS_TOKEN_LOGS.
	//
	//    * For Amazon VPC Route Server, the valid value is EVENT_LOGS.
	//
	// Regex Pattern: `^[\w]*$`
	// +kubebuilder:validation:Required
	LogType *string `json:"logType"`
	// A name for this delivery source. This name must be unique for all delivery
	// sources in your account.
	//
	// Regex Pattern: `^[\w-]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The ARN of the Amazon Web Services resource that is generating and sending
	// logs. For example, arn:aws:workmail:us-east-1:123456789012:organization/m-1234EXAMPLEabcd1234abcd1234abcd1234
	// +kubebuilder:validation:Required
	ResourceARN *string `json:"resourceARN"`
	// An optional list of key-value pairs to associate with the resource.
	//
	// For more information about tagging, see Tagging Amazon Web Services resources
	// (https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html)
	Tags map[string]*string `json:"tags,omitempty"`
}

// DeliverySourceStatus defines the observed state of DeliverySource
type DeliverySourceStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// This array contains the ARN of the Amazon Web Services resource that sends
	// logs and is represented by this delivery source. Currently, only one ARN
	// can be in the array.
	// +kubebuilder:validation:Optional
	ResourceARNs []*string `json:"resourceARNs,omitempty"`
	// The Amazon Web Services service that is sending logs.
	//
	// Regex Pattern: `^[\w_-]*$`
	// +kubebuilder:validation:Optional
	Service *string `json:"service,omitempty"`
}

// DeliverySource is the Schema for the DeliverySources API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type DeliverySource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DeliverySourceSpec   `json:"spec,omitempty"`
	Status            DeliverySourceStatus `json:"status,omitempty"`
}

// DeliverySourceList contains a list of DeliverySource
// +kubebuilder:object:root=true
type DeliverySourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DeliverySource `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DeliverySource{}, &DeliverySourceList{})
}
