// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ImportTaskSpec defines the desired state of ImportTask.
type ImportTaskSpec struct {

	// Optional filters to constrain the import by CloudTrail event time. Times
	// are specified in Unix timestamp milliseconds. The range of data being imported
	// must be within the specified source's retention period.
	ImportFilter *ImportFilter `json:"importFilter,omitempty"`
	// The ARN of the IAM role that grants CloudWatch Logs permission to import
	// from the CloudTrail Lake Event Data Store.
	// +kubebuilder:validation:Required
	ImportRoleARN *string `json:"importRoleARN"`
	// The ARN of the source to import from.
	// +kubebuilder:validation:Required
	ImportSourceARN *string `json:"importSourceARN"`
}

// ImportTaskStatus defines the observed state of ImportTask
type ImportTaskStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the import task was created, expressed as the number of
	// milliseconds after Jan 1, 1970 00:00:00 UTC.
	// +kubebuilder:validation:Optional
	CreationTime *int64 `json:"creationTime,omitempty"`
	// The ARN of the CloudWatch Logs log group created as the destination for the
	// imported events.
	// +kubebuilder:validation:Optional
	ImportDestinationARN *string `json:"importDestinationARN,omitempty"`
	// A unique identifier for the import task.
	//
	// Regex Pattern: `^[\-a-zA-Z0-9]+$`
	// +kubebuilder:validation:Optional
	ImportID *string `json:"importID,omitempty"`
}

// ImportTask is the Schema for the ImportTasks API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ImportTask struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ImportTaskSpec   `json:"spec,omitempty"`
	Status            ImportTaskStatus `json:"status,omitempty"`
}

// ImportTaskList contains a list of ImportTask
// +kubebuilder:object:root=true
type ImportTaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ImportTask `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ImportTask{}, &ImportTaskList{})
}
